spring.application.name=smart-emp-mgmt

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Employee_Management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=Badhri

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=c21hcnRlbXBtZ210c2VjcmV0a2V5Zm9yandzaWduaW5nMjAyNmV2ZXJub3J0aA==
app.jwt.expiration-ms=86400000

logging.level.com.evernorth.smartemp=DEBUG
springdoc.swagger-ui.path=/swagger-ui.html
