package com.evernorth.smartemp.service;
import com.evernorth.smartemp.dto.EmployeeDto; import com.evernorth.smartemp.entity.User; import com.evernorth.smartemp.enums.Role; import com.evernorth.smartemp.exception.*; import com.evernorth.smartemp.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.util.*;
@Service @RequiredArgsConstructor public class EmployeeService {private final UserRepository repo; private final PasswordEncoder enc;
 public Page<EmployeeDto.Response> search(String s,String d,Pageable p){return repo.search(s,d,p).map(this::toResponse);} public List<EmployeeDto.Response> listAll(){return repo.findAll().stream().map(this::toResponse).toList();}
 public EmployeeDto.Response create(EmployeeDto.Request r){if(repo.existsByUsername(r.getUsername())||repo.existsByEmail(r.getEmail()))throw new BadRequestException("Username or email already exists");if(r.getPassword()==null||r.getPassword().isBlank())throw new BadRequestException("Password is required");User u=map(new User(),r);u.setPassword(enc.encode(r.getPassword()));return toResponse(repo.save(u));}
 public EmployeeDto.Response update(Long id,EmployeeDto.Request r){User u=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Employee not found"));map(u,r);if(r.getPassword()!=null&&!r.getPassword().isBlank())u.setPassword(enc.encode(r.getPassword()));if(r.getRoles()!=null)u.setRoles(roles(r.getRoles()));return toResponse(repo.save(u));}
 public void delete(Long id){if(id==1L)throw new BadRequestException("Cannot delete primary administrator");if(!repo.existsById(id))throw new ResourceNotFoundException("Employee not found");repo.deleteById(id);}
 private User map(User u,EmployeeDto.Request r){u.setUsername(r.getUsername());u.setEmail(r.getEmail());u.setFirstName(r.getFirstName());u.setLastName(r.getLastName());u.setDepartment(r.getDepartment());u.setDesignation(r.getDesignation());u.setSalary(r.getSalary());u.setPhone(r.getPhone());if(r.getRoles()!=null)u.setRoles(roles(r.getRoles()));return u;} private Set<Role> roles(List<String> rs){Set<Role>x=new HashSet<>();rs.forEach(s->x.add(Role.valueOf(s.replace("ROLE_",""))));return x;} public EmployeeDto.Response toResponse(User u){return EmployeeDto.Response.builder().id(u.getId()).username(u.getUsername()).email(u.getEmail()).firstName(u.getFirstName()).lastName(u.getLastName()).department(u.getDepartment()).designation(u.getDesignation()).salary(u.getSalary()).phone(u.getPhone()).hireDate(u.getHireDate()).roles(u.getRoles().stream().map(Enum::name).toList()).build();} public EmployeeDto.Summary toSummary(User u){return EmployeeDto.Summary.builder().id(u.getId()).firstName(u.getFirstName()).lastName(u.getLastName()).designation(u.getDesignation()).build();}
}
